### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by tpoisot** [BIO6032/2019_replication_HastingsPowell_1991#1]
### General ###
- [x] Get used to Gitub 
- [x] Get used to Julia
- [x] Get used to Atom
- [x] Read a few paper that cited Hastings & Powell (1991) @gabrieldansereau @ElodieBsq 

### Model ###
- [x]  Integrate numerically the differential equations @FrancisBanville 

### Model ###
- [x] Replicate Figure 2 @gabrieldansereau 
- [x] Replicate Figure 4 @gabrieldansereau 
- [x] Replicate Figure 5 @FrancisBanville 

### Model ###
- [x] Replicate Figure 3 @ElodieBsq 
- [x] Reorganize function and figure files @ElodieBsq 
- [x] Look for functions for Poincaré sections @FrancisBanville 
- [x] Look for functions for local maxima  @gabrieldansereau 
- [x] Make Figure 5 pretty @FrancisBanville 
- [x] Make tea cup GIF @FrancisBanville
- [x] Verify how to parametrize the loop for Figure 4 @gabrieldansereau 
- [x] Choose adequate algorithm for ODE @BIO6032/2019ebfbgd 
- [x] Choose initial values @BIO6032/2019ebfbgd 

### Paper ###
- [x] Look if the model has already been replicated @gabrieldansereau 

### Model ###

- [x] Figure 4: find a way to remove second local maxima @aammd @gabrieldansereau 
- [x] Make final choice of initial values and algorithm @BIO6032/2019ebfbgd 
- [x] Make the code & figures functional, replicable and pretty @BIO6032/2019ebfbgd 

### Paper ###

- [x] First draft
- [x] Introduction @ElodieBsq 
- [x] Methods @gabrieldansereau
- [x] Results + figure captions @FrancisBanville 
- [x] Discussion @FrancisBanville 
- [x] Conclusion @ElodieBsq 

### Model ###
- [x] Grid lines on flipped 3D plots @BIO6032/2019ebfbgd 

### Paper ###
- [x] Traduction in Markdown/LaTeX @gabrieldansereau 
- [x] Final version @BIO6032/2019ebfbgd 

### Figures
- Figure 2D
  - [x] Add grid lines (#6 )
  - [x] Keep values of t = 5000-10 000 only (#13)
- Figure 5 
  - [x] Finalize value selection, or explanation of difference with H&P (#7)
  - [x] Keep values of t = 5000-10 000 only (#13)
- Teacup GIF
  - [x] Line transparency, add to README (#14)
- General
  - [x] Figure identification letters & subtitles (#8)
  - [x] Make figures harmonious and pretty (#10)

### Code
- [x] Homogenize code structure/syntax/comments (#11)

### Other
- [x] YAML file for submission (#16) @gabrieldansereau 
- [x] Update README
